[project]
name = "ghost2lead-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "pydantic-settings>=2.12.0",
    "scalar-fastapi>=1.6.1",
    "uvicorn[standard]>=0.40.0",
]
